### ISSUE TITLE
google facebook 都打不开 chn

### ISSUE THREAD

**Issue by warmonipa** [Ricky-Hao/SSTAP_Rules#2]
内网地址也打不开 ，比如路由器，youtube视频页面可以打开，但是视频打不开

**Comment by Ricky-Hao** [comment]
你的dns对吗？有被污染吗？sstap不适用于日常使用，比较适用于打游戏。日常使用推荐proxifier和switchyomega。

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by warmonipa** [comment]
> 你的dns对吗？有被污染吗？sstap不适用于日常使用，比较适用于打游戏。日常使用推荐proxifier和switchyomega。 获取 Outlook for Android<https://aka.ms/ghei36>

我的dns应该没问题，开其他代理就可以，只是想了解下普通网页代理是否可行，看了你生成的规则，not 国内ip地址段
